"""baseline

Revision ID: a6894f76515b
Revises: 
Create Date: 2026-07-04 18:00:36.256270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6894f76515b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('type', sa.Enum('sprint', 'tempo', 'easy_run', 'hike', 'ruck', 'strength', name='activitytype'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('hr_zones', sa.JSON(), nullable=True),
    sa.Column('load_kg', sa.Float(), nullable=True),
    sa.Column('splits', sa.JSON(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('source', 'external_id', name='uq_activity_source_ext')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_start_time'), ['start_time'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)

    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('sleep_duration_min', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('mood_valence', sa.Float(), nullable=True),
    sa.Column('mood_energy', sa.Float(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_summaries'))
    )
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_summaries_day'), ['day'], unique=True)

    op.create_table('listening_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('track_name', sa.String(length=256), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('tempo', sa.Float(), nullable=True),
    sa.Column('genre', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_sessions'))
    )
    with op.batch_alter_table('listening_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listening_sessions_played_at'), ['played_at'], unique=True)

    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=256), nullable=True),
    sa.Column('athlete_id', sa.String(length=64), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_tokens')),
    sa.UniqueConstraint('provider', name=op.f('uq_oauth_tokens_provider'))
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('oauth_tokens')
    with op.batch_alter_table('listening_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listening_sessions_played_at'))

    op.drop_table('listening_sessions')
    with op.batch_alter_table('daily_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_summaries_day'))

    op.drop_table('daily_summaries')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_start_time'))

    op.drop_table('activities')
    # ### end Alembic commands ###
