"""wellness samples

Revision ID: b26bb82e891a
Revises: 286c43fab6ec
Create Date: 2026-07-05 12:43:13.985763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26bb82e891a'
down_revision: Union[str, None] = '286c43fab6ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wellness_samples')),
    sa.UniqueConstraint('source', 'kind', 'recorded_at', name='uq_wellness_source_kind_time')
    )
    with op.batch_alter_table('wellness_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wellness_samples_recorded_at'), ['recorded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wellness_samples_recorded_at'))

    op.drop_table('wellness_samples')
    # ### end Alembic commands ###
